name: Auto Replace Image URLs
on: [push]
jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Replace URLs
        run: |
          # 替换 GitHub Raw 绝对路径
          find . -name "*.html" -exec sed -i 's|https://raw\.githubusercontent\.com/psterman/dlqpy/main/pic/|https://cdn.jsdelivr.net/gh/psterman/dlqpy@main/pic/|g' {} +

          # 替换相对路径（兼容 src="/pic/ 或 src="pic/）
          find . -name "*.html" -exec sed -i -E 's|src=["'\'']/?(pic/)|\1|g; s|(src=["'\''])(pic/)|\1https://cdn.jsdelivr.net/gh/psterman/dlqpy@main/\2|g' {} +

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet || (git commit -m "Auto: Replace image URLs" && git push)